name: Deploy React Calculator

on:
  push:
    branches: [main]
    paths:
      - 'lab06_2/calculator/**'  

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install and build
        run: |
          cd lab06_2/calculator  # Правильный путь к вашему проекту
          npm install
          npm run build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: lab06_2/calculator/build  
